debuggando

diff --git a/.github/workflows/deploy-firebase.yml b/.github/workflows/deploy-firebase.yml
--- a/.github/workflows/deploy-firebase.yml
+++ b/.github/workflows/deploy-firebase.yml
@@ -34,18 +34,29 @@ jobs:
     - name: Build Angular app
       run: npm run build:prod
 
+    # Debugging: Show GitHub ref
+    - name: Show GITHUB_REF
+      run: echo "GITHUB_REF is $GITHUB_REF"
+
     # Deploy to Firebase Hosting :D
     - name: Deploy to Firebase Hosting
       env:
         FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SOLICITOU_DESENVOLVIMENTO }}
       run: |
+        set -e # Fail on first error to stop pipeline
+        echo "Starting Firebase deploy script..."
         if [[ "$GITHUB_REF" == "refs/heads/develop" ]]; then
+          echo "Deploying to Desenvolvimento environment..."
           firebase use solicitou-desenvolvimento --token $FIREBASE_TOKEN
           firebase deploy --only hosting:solicitou-web-desenvolvimento --token $FIREBASE_TOKEN
         elif [[ "$GITHUB_REF" == "refs/heads/homolog" ]]; then
+          echo "Deploying to Homologacao environment..."
           firebase use solicitou-homologacao --token $FIREBASE_TOKEN
           firebase deploy --only hosting:solicitou-web-homologacao --token $FIREBASE_TOKEN
         elif [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
+          echo "Deploying to Producao environment..."
           firebase use solicitou-producao --token $FIREBASE_TOKEN
           firebase deploy --only hosting:solicitou-web-producao --token $FIREBASE_TOKEN
+        else
+          echo "No matching branch found, skipping deploy."
         fi
